### ISSUE TITLE
Intel Wifi soldered 8260

### ISSUE THREAD

**Issue by johnnynunez** [AppleIntelWifi/device-logs#13]
Xiaomi Air laptop
[log.txt](https://github.com/AppleIntelWifi/device-logs/files/4428178/log.txt)

I can search my wpa2 wifi, turn on/off
<img width="466" alt="Screenshot 2020-04-03 at 17 14 20" src="https://user-images.githubusercontent.com/22727137/78376515-be060600-75ce-11ea-9b7c-8f2dfc21e1fc.png">

**Comment by georgkreimer** [comment]
Mind attaching the kext? Can't load the one I built from source
