### ISSUE TITLE
Unable to find 5G wifi signal【intel 8265】

### ISSUE THREAD

**Issue by zzz6839** [AppleIntelWifi/device-logs#15]
[log.txt](https://github.com/AppleIntelWifi/device-logs/files/4430478/log.txt)

**Comment by zzz6839** [comment]
good to see it scanning but unable to find my home wifi ;)

**Comment by rv32ima** [comment]
What do you mean? It's clearly finding it:
```
kernel: (AppleIntelWifiAdapterV2) AppleIntelWifiAdapter INFO: Scan result (SSID: Huawei, channel: 149, RSSI: 37)
```

**Comment by zzz6839** [comment]
I added it manually just to try to connect it but failed（could not join and find, or at least cannot see this SSID on interface menu）

**Comment by zzz6839** [comment]
good work! The latest build can discover 5G wifi now, but cant connect it, i'll keep waiting.
